@echo off
setlocal enabledelayedexpansion

echo 正在初始化 AI-Operating-System-V2 架構...

:: 建立根目錄
mkdir AI-Operating-System-V2
cd AI-Operating-System-V2

:: 00_SYSTEM_CORE
mkdir 00_SYSTEM_CORE
echo # START_HERE > 00_SYSTEM_CORE\START_HERE.md
echo # SYSTEM_VISION > 00_SYSTEM_CORE\SYSTEM_VISION.md
echo # SYSTEM_ARCHITECTURE > 00_SYSTEM_CORE\SYSTEM_ARCHITECTURE.md
echo # AI_BEHAVIOR_RULES > 00_SYSTEM_CORE\AI_BEHAVIOR_RULES.md
echo # FILE_NAMING_STANDARD > 00_SYSTEM_CORE\FILE_NAMING_STANDARD.md

:: 01_SYSTEM_RULES
mkdir 01_SYSTEM_RULES

:: 02_SCHEMAS
mkdir 02_SCHEMAS
echo # MEETING_SCHEMA > 02_SCHEMAS\MEETING_SCHEMA.md
echo # PROJECT_SCHEMA > 02_SCHEMAS\PROJECT_SCHEMA.md
echo # RISK_SCHEMA > 02_SCHEMAS\RISK_SCHEMA.md
echo # PPT_SCHEMA > 02_SCHEMAS\PPT_SCHEMA.md

:: 03_WORKFLOWS
mkdir 03_WORKFLOWS
echo # WORKFLOW_STANDARD > 03_WORKFLOWS\WORKFLOW_STANDARD.md
echo # KNOWLEDGE_RETRIEVAL_WORKFLOW > 03_WORKFLOWS\KNOWLEDGE_RETRIEVAL_WORKFLOW.md
echo # PPT_WORKFLOW > 03_WORKFLOWS\PPT_WORKFLOW.md

:: 04_DOMAIN_KNOWLEDGE (含子目錄)
mkdir 04_DOMAIN_KNOWLEDGE\Automation
mkdir 04_DOMAIN_KNOWLEDGE\Customers
mkdir 04_DOMAIN_KNOWLEDGE\Robotics
mkdir 04_DOMAIN_KNOWLEDGE\Manufacturing
mkdir 04_DOMAIN_KNOWLEDGE\Lessons_Learned

:: 05_AI_MEMORY (含子目錄)
mkdir 05_AI_MEMORY\Short_Term
mkdir 05_AI_MEMORY\Long_Term
mkdir 05_AI_MEMORY\Customer_Context
mkdir 05_AI_MEMORY\Project_Context
mkdir 05_AI_MEMORY\Archived_Memory

:: 06 ~ 08 系統目錄
mkdir 06_PM_SYSTEM
mkdir 07_PRESENTATION_SYSTEM
mkdir 08_EXECUTION_ENGINE

:: 09_VALIDATION
mkdir 09_VALIDATION
echo # VALIDATION_RULES > 09_VALIDATION\VALIDATION_RULES.md

:: 10 ~ 11
mkdir 10_ARCHIVE
mkdir 11_SANDBOX

:: 99_PROJECT_MANAGEMENT
mkdir 99_PROJECT_MANAGEMENT
echo # PROJECT_ROADMAP > 99_PROJECT_MANAGEMENT\PROJECT_ROADMAP.md
echo # CHANGELOG > 99_PROJECT_MANAGEMENT\CHANGELOG.md
echo # VERSION_HISTORY > 99_PROJECT_MANAGEMENT\VERSION_HISTORY.md

echo.
echo ✅ AI-Operating-System-V2 架構建立完成！
pause
